### ISSUE TITLE
Description more about cybersecurity collection

### ISSUE THREAD

**Issue by LAVANSURESH** [Anish-M-code/CyberSecurity-Collection#1]
What will happen if i execute **notepad++_hack.exe** in my system

**Comment by Anish-M-code** [comment]
if notepad++_hack.exe is run in a windows computer , it will first open command prompt and print this program was developed by M.Anish etc , then it will just open the default browser and make the user visit
https://kali.org . 

The command prompt will stay open until user enters some input or closes it manually.

The strings present inside system() is actually windows batch processing commands/ commands which can be executed by Command prompt.
